SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;

USE test_db;
SET autocommit = 0;

START TRANSACTION;
SELECT *
FROM users
WHERE name LIKE '%Users%';

DO SLEEP(10);

SELECT *
FROM users
WHERE name LIKE '%Users%';
COMMIT;